version: '3.2'
services:
  db:
    image: mysql:5
    ports: # this opens the guest MySQL port to the host OS
      - "3316:3316"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --port 3316

  redis:
    image: redis:5-alpine

  web:
    build: .
    command: bin/rails server --port 3060 --binding 0.0.0.0
    ports: # this opens the guest Rails port to the host OS
      - "3060:3060"
    links:
      - db
      - redis
    volumes:
      - .:/ir_investidor
      - volume_ir_investidor:/bundle

  sidekiq:
    build: .
    command: bundle exec sidekiq -C config/sidekiq.yml
    links:
      - db
      - redis
    volumes:
      - .:/ir_investidor
      - volume_ir_investidor:/bundle

volumes:
  volume_ir_investidor:
